### PR TITLE
Upgrade to Bevy 0.4.

### PR DESCRIPTION
**Pull request by ndarilek**

### CODE REVIEW

**Comment by PradeepKumarRajamanickam** [comment]
Hey @ndarilek ,  There are changes that are not related to bevy upgrade in this or i.e. code formatting, parameter aligning change...etc. They should not be part of this request.

**Comment by ndarilek** [comment]
Done.

**Review by PradeepKumarRajamanickam — APPROVED** [review]
LGTM

**Comment by PradeepKumarRajamanickam** [comment]
@ndarilek Thank you for the pr.

**Pull request merged**
